services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    networks:
      - nginx-php81-mysql8

  php81-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php81-mysql8

  mysql8-service:
    image: mysql:8.0
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_DATABASE: "app"
    networks:
      - nginx-php81-mysql8

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    links:
      - mysql8-service
    environment:
      PMA_HOST: mysql8-service
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - nginx-php81-mysql8

networks:
  nginx-php81-mysql8:
    driver: bridge
